further reworked rust CI (#489)
note that this CI now checks for dirty git repo - so no more temp files
created but not `.gitignore`-d. There is a file one of the unit tests
creates - i moved it to `/target` dir.

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -1,74 +1,97 @@
-name: Build
+name: Rust CI
 
 on:
   push:
-    branches: [ "main" ]
+    branches: [ main ]
   pull_request:
-    branches: [ "main" ]
+    branches: [ main ]
   release:
     types: [ published ]
   workflow_dispatch:
 
 defaults:
   run:
-    working-directory: ./rust
+    shell: bash
+    working-directory: ./rust/mlt
 
 jobs:
   test:
+    name: Test
     runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: ./rust/mlt
     steps:
-      - uses: taiki-e/install-action@v2
-        with: { tool: just }
       - uses: actions/checkout@v4
-      - name: Install protoc
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y protobuf-compiler
       - if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
         uses: Swatinem/rust-cache@v2
-      - run: just -v ci-test
-      #
-      # Uncomment this and below once the crate has been published to crates.io
-      #
-      # - if: github.event_name == 'release' && matrix.type == 'latest'
-      #   name: Ensure this crate has not yet been published (on release)
-      #   run: just check-if-published
-      # - name: Check semver
-      #   uses: obi1kenobi/cargo-semver-checks-action@v2
-      # - name: Test packaging for publish
-      #   run: |
-      #     rustup install nightly --profile minimal
-      #     just test-publish
+      - uses: taiki-e/install-action@v2
+        with: { tool: just }
+      #- if: github.event_name == 'release'
+      #  name: Ensure this crate has not yet been published (on release)
+      #  run: just check-if-published
+      - name: Install protoc
+        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
+      - run: just ci-test
+      #- name: Check semver
+      #  uses: obi1kenobi/cargo-semver-checks-action@v2
 
-  msrv:
+  test-msrv:
     name: Test MSRV
     runs-on: ubuntu-latest
-    defaults:
-      run:
-        working-directory: ./rust/mlt
     steps:
-      - uses: taiki-e/install-action@v2
-        with: { tool: just }
       - uses: actions/checkout@v4
-      - name: Install protoc
-        run: |
-          sudo apt-get update
-          sudo apt-get install -y protobuf-compiler
       - if: github.event_name != 'release' && github.event_name != 'workflow_dispatch'
         uses: Swatinem/rust-cache@v2
-      - name: Read crate metadata
+      - uses: taiki-e/install-action@v2
+        with: { tool: just }
+      - name: Install protoc
+        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
+      - name: Read MSRV
         id: msrv
-        run: |
-          CRATE_NAME=mlt
-          msrv="$(cargo metadata --format-version 1 | jq -r --arg CRATE_NAME "$CRATE_NAME"  '.packages | map(select(.name == $CRATE_NAME)) | first | .rust_version')"
-          echo "MSRV for crate $CRATE_NAME is '$msrv'"
-          echo "value=$msrv" >> $GITHUB_OUTPUT
-      - name: Install Rust
+        run: echo "value=$(just get-msrv)" >> $GITHUB_OUTPUT
+      - name: Install MSRV Rust ${{ steps.msrv.outputs.value }}
         uses: dtolnay/rust-toolchain@stable
         with:
           toolchain: ${{ steps.msrv.outputs.value }}
-          components: rustfmt
-      - run: just -v ci-test-msrv
+      - run: just ci_mode=0 ci-test-msrv  # Ignore warnings in MSRV
+
+  coverage:
+    name: Code Coverage
+    if: github.event_name != 'release'
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: Swatinem/rust-cache@v2
+      - uses: taiki-e/install-action@v2
+        with: { tool: 'just,cargo-llvm-cov' }
+      - name: Install protoc
+        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
+      - name: Generate code coverage
+        run: just ci-coverage
+      - name: Upload coverage to Codecov
+        uses: codecov/codecov-action@v5
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }}
+          files: target/llvm-cov/codecov.info
+          fail_ci_if_error: true
+
+  # This job checks if any of the previous jobs failed or were canceled.
+  # This approach also allows some jobs to be skipped if they are not needed.
+  ci-passed:
+    if: always()
+    needs: [ test, test-msrv ]
+    runs-on: ubuntu-latest
+    steps:
+      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
+        run: exit 1
+
+  release:
+    # Some dependencies of the `ci-passed` job might be skipped, but we still want to run if the `ci-passed` job succeeded.
+    if: always() && startsWith(github.ref, 'refs/tags/') && needs.ci-passed.result == 'success'
+    name: Publish to crates.io
+    needs: [ ci-passed ]
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Publish to crates.io
+        run: cargo publish
+        env:
+          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
diff --git a/rust/mlt/justfile b/rust/mlt/justfile
--- a/rust/mlt/justfile
+++ b/rust/mlt/justfile
@@ -1,30 +1,39 @@
 #!/usr/bin/env just --justfile
 
+main_crate := 'mlt'
+features_flag := '--all-features'
+
+# if running in CI, treat warnings as errors by setting RUSTFLAGS and RUSTDOCFLAGS to '-D warnings' unless they are already set
+# Use `CI=true just ci-test` to run the same tests as in GitHub CI.
+# Use `just env-info` to see the current values of RUSTFLAGS and RUSTDOCFLAGS
+ci_mode := if env('CI', '') != '' {'1'} else {''}
+export RUSTFLAGS := env('RUSTFLAGS', if ci_mode == '1' {'-D warnings'} else {''})
+export RUSTDOCFLAGS := env('RUSTDOCFLAGS', if ci_mode == '1' {'-D warnings'} else {''})
+export RUST_BACKTRACE := env('RUST_BACKTRACE', if ci_mode == '1' {'1'} else {''})
+
 @_default:
-    just --list
+    {{just_executable()}} --list
 
-# Run tests, and accept their results. Requires insta to be installed.
-bless:
-    TRYBUILD=overwrite cargo insta test --accept
+# Run integration tests and save its output as the new expected output
+bless *args:  (cargo-install 'cargo-insta')
+    TRYBUILD=overwrite cargo insta test --accept --unreferenced=delete {{features_flag}} {{args}}
 
-# Default build
+# Build the project
 build:
-    cargo build --all-targets --workspace
+    cargo build --workspace --all-targets {{features_flag}}
 
-# Quick compile
+# Quick compile without building a binary
 check:
-    cargo check --all-targets --workspace
+    cargo check --workspace --all-targets {{features_flag}}
 
 # Verify that the current version of the crate is not the same as the one published on crates.io
-check-if-published:
+check-if-published package=main_crate:  (assert-cmd 'jq')
     #!/usr/bin/env bash
     set -euo pipefail
-    LOCAL_VERSION="$(grep '^version =' Cargo.toml | sed -E 's/version = "([^"]*)".*/\1/')"
-    echo "Detected crate version:  $LOCAL_VERSION"
-    CRATE_NAME="$(grep '^name =' Cargo.toml | head -1 | sed -E 's/name = "(.*)"/\1/')"
-    echo "Detected crate name:     $CRATE_NAME"
-    PUBLISHED_VERSION="$(cargo search ${CRATE_NAME} | grep "^${CRATE_NAME} =" | sed -E 's/.* = "(.*)".*/\1/')"
-    echo "Published crate version: $PUBLISHED_VERSION"
+    LOCAL_VERSION="$({{just_executable()}} get-crate-field version package)"
+    echo "Detected crate {{package}} version:  '$LOCAL_VERSION'"
+    PUBLISHED_VERSION="$(cargo search --quiet {{package}} | grep "^{{package}} =" | sed -E 's/.* = "(.*)".*/\1/')"
+    echo "Published crate version: '$PUBLISHED_VERSION'"
     if [ "$LOCAL_VERSION" = "$PUBLISHED_VERSION" ]; then
         echo "ERROR: The current crate version has already been published."
         exit 1
@@ -32,65 +41,79 @@ check-if-published:
         echo "The current crate version has not yet been published."
     fi
 
-# Run all tests as expected by CI
-ci-test: rust-info test-fmt clippy test build
+# Generate code coverage report to upload to codecov.io
+ci-coverage: env-info && \
+            (coverage '--codecov --output-path target/llvm-cov/codecov.info')
+    # ATTENTION: the full file path above is used in the CI workflow
+    mkdir -p target/llvm-cov
 
-# Run tests only relevant to the latest version
-ci-test-extras: test-doc
+# Run all tests as expected by CI
+ci-test: env-info test-fmt clippy check test test-doc && assert-git-is-clean
 
 # Run minimal subset of tests to ensure compatibility with MSRV
-ci-test-msrv: rust-info test
+ci-test-msrv: env-info check test
 
 # Clean all build artifacts
 clean:
     cargo clean
     rm -f Cargo.lock
 
-# Run cargo clippy
-clippy:
-    cargo clippy --all-targets --workspace -- -D warnings
+# Run cargo clippy to lint the code
+clippy *args:
+    cargo clippy --workspace --all-targets {{features_flag}} {{args}}
+
+# Generate code coverage report. Will install `cargo llvm-cov` if missing.
+coverage *args='--no-clean --open':  (cargo-install 'cargo-llvm-cov')
+    cargo llvm-cov --workspace --all-targets {{features_flag}} --include-build-script {{args}}
 
 # Build and open code documentation
-docs:
-    cargo doc --no-deps --open
+docs *args='--open':
+    DOCS_RS=1 cargo doc --no-deps {{args}} --workspace {{features_flag}}
 
-# Run cargo fmt
-fmt:
-    cargo +nightly fmt -- --config imports_granularity=Module,group_imports=StdExternalCrate
-
-# Generate and show coverage report. Requires grcov to be installed.
-grcov:
-    #!/usr/bin/env bash
-    set -euo pipefail
-    find . -name '*.profraw' | xargs rm
-    rm -rf ./target/debug/coverage
-    export LLVM_PROFILE_FILE="mlt-%p-%m.profraw"
-    export RUSTFLAGS="-Cinstrument-coverage"
-    cargo build --all-targets --workspace
-    cargo test --all-targets --workspace
-    grcov . -s . --binary-path ./target/debug/ -t html --branch --ignore-not-existing -o ./target/debug/coverage/
-    open ./target/debug/coverage/index.html
-
-# Find the minimum supported Rust version. Install it with `cargo install cargo-msrv`
-msrv:
-    cargo msrv find --component rustfmt -- {{just_executable()}} ci-test-msrv
-
-rust-info:
+# Print environment info
+env-info:
+    @echo "Running {{if ci_mode == '1' {'in CI mode'} else {'in dev mode'} }} on {{os()}} / {{arch()}}"
+    {{just_executable()}} --version
     rustc --version
     cargo --version
+    rustup --version
+    @echo "RUSTFLAGS='$RUSTFLAGS'"
+    @echo "RUSTDOCFLAGS='$RUSTDOCFLAGS'"
+
+# Reformat all code `cargo fmt`. If nightly is available, use it for better results
+fmt:
+    #!/usr/bin/env bash
+    set -euo pipefail
+    if rustup component list --toolchain nightly | grep rustfmt &> /dev/null; then
+        echo 'Reformatting Rust code using nightly Rust fmt to sort imports'
+        cargo +nightly fmt --all -- --config imports_granularity=Module,group_imports=StdExternalCrate
+    else
+        echo 'Reformatting Rust with the stable cargo fmt.  Install nightly with `rustup install nightly` for better results'
+        cargo fmt --all
+    fi
+
+# Get any package's field from the metadata
+get-crate-field field package=main_crate:
+    cargo metadata --format-version 1 | jq -r '.packages | map(select(.name == "{{package}}")) | first | .{{field}}'
+
+# Get the minimum supported Rust version (MSRV) for the crate
+get-msrv package=main_crate:  (get-crate-field 'rust_version' package)
+
+# Find the minimum supported Rust version (MSRV) using cargo-msrv extension, and update Cargo.toml
+msrv:  (cargo-install 'cargo-msrv')
+    cargo msrv find --write-msrv --ignore-lockfile --component rustfmt -- {{just_executable()}} ci-test-msrv
 
 # Check semver compatibility with prior published version. Install it with `cargo install cargo-semver-checks`
-semver *ARGS:
-    cargo semver-checks {{ARGS}}
+semver *args:  (cargo-install 'cargo-semver-checks')
+    cargo semver-checks {{features_flag}} {{args}}
 
 # Run all tests
-test *ARGS: build
-    cargo test --all-targets --workspace {{ARGS}}
+test:
+    cargo test --workspace --all-targets {{features_flag}}
+    cargo test --workspace --doc {{features_flag}}
 
-# Test documentation
-test-doc:
-    cargo test --doc
-    cargo doc --no-deps
+# Test documentation generation
+test-doc:  (docs '')
 
 # Test code formatting
 test-fmt:
@@ -101,10 +124,44 @@ test-publish:
     cargo +nightly -Z package-workspace publish --dry-run
 
 # Find unused dependencies. Install it with `cargo install cargo-udeps`
-udeps:
-    cargo +nightly udeps --all-targets --workspace
+udeps:  (cargo-install 'cargo-udeps')
+    cargo +nightly udeps --workspace --all-targets {{features_flag}}
 
-# Update dependencies, including breaking changes
+# Update all dependencies, including breaking changes. Requires nightly toolchain (install with `rustup install nightly`)
 update:
     cargo +nightly -Z unstable-options update --breaking
     cargo update
+
+# Ensure that a certain command is available
+[private]
+assert-cmd command:
+    @if ! type {{command}} > /dev/null; then \
+        echo "Command '{{command}}' could not be found. Please make sure it has been installed on your computer." ;\
+        exit 1 ;\
+    fi
+
+# Make sure the git repo has no uncommitted changes
+[private]
+assert-git-is-clean:
+    @if [ -n "$(git status --untracked-files --porcelain)" ]; then \
+      >&2 echo "ERROR: git repo is no longer clean. Make sure compilation and tests artifacts are in the .gitignore, and no repo files are modified." ;\
+      >&2 echo "######### git status ##########" ;\
+      git status ;\
+      git --no-pager diff ;\
+      exit 1 ;\
+    fi
+
+# Check if a certain Cargo command is installed, and install it if needed
+[private]
+cargo-install $COMMAND $INSTALL_CMD='' *args='':
+    #!/usr/bin/env bash
+    set -euo pipefail
+    if ! command -v $COMMAND > /dev/null; then
+        if ! command -v cargo-binstall > /dev/null; then
+            echo "$COMMAND could not be found. Installing it with    cargo install ${INSTALL_CMD:-$COMMAND} --locked {{args}}"
+            cargo install ${INSTALL_CMD:-$COMMAND} --locked {{args}}
+        else
+            echo "$COMMAND could not be found. Installing it with    cargo binstall ${INSTALL_CMD:-$COMMAND} --locked {{args}}"
+            cargo binstall ${INSTALL_CMD:-$COMMAND} --locked {{args}}
+        fi
+    fi
